name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch tags
        run: git fetch --tags

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v6
        with:
          go-version: '1.25.x'

      - uses: buildpacks/github-actions/setup-pack@v5.12.4

      - name: Run tests
        run: make tests

      - name: Publish builders
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make publish_builders

      - name: Publish jupyterlab frontend sample
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make publish_sample_coding-agent FRONTEND=jupyterlab

      - name: Publish vscodium frontend sample
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make publish_sample_coding-agent FRONTEND=vscodium

      - name: Publish ttyd frontend sample
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make publish_sample_coding-agent FRONTEND=ttyd
