name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-go@v6

      - uses: buildpacks/github-actions/setup-pack@v5.12.4

      - name: Run tests
        run: make tests

      - name: Publish builders
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: make publish_builders
